// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package users_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UsersProtoInterfaceClient is the client API for UsersProtoInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersProtoInterfaceClient interface {
	GetUserByUuid(ctx context.Context, in *Uuid, opts ...grpc.CallOption) (*UserMsgResponse, error)
}

type usersProtoInterfaceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersProtoInterfaceClient(cc grpc.ClientConnInterface) UsersProtoInterfaceClient {
	return &usersProtoInterfaceClient{cc}
}

func (c *usersProtoInterfaceClient) GetUserByUuid(ctx context.Context, in *Uuid, opts ...grpc.CallOption) (*UserMsgResponse, error) {
	out := new(UserMsgResponse)
	err := c.cc.Invoke(ctx, "/flydev_chat_app_users.UsersProtoInterface/GetUserByUuid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersProtoInterfaceServer is the server API for UsersProtoInterface service.
// All implementations must embed UnimplementedUsersProtoInterfaceServer
// for forward compatibility
type UsersProtoInterfaceServer interface {
	GetUserByUuid(context.Context, *Uuid) (*UserMsgResponse, error)
	mustEmbedUnimplementedUsersProtoInterfaceServer()
}

// UnimplementedUsersProtoInterfaceServer must be embedded to have forward compatible implementations.
type UnimplementedUsersProtoInterfaceServer struct {
}

func (UnimplementedUsersProtoInterfaceServer) GetUserByUuid(context.Context, *Uuid) (*UserMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByUuid not implemented")
}
func (UnimplementedUsersProtoInterfaceServer) mustEmbedUnimplementedUsersProtoInterfaceServer() {}

// UnsafeUsersProtoInterfaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersProtoInterfaceServer will
// result in compilation errors.
type UnsafeUsersProtoInterfaceServer interface {
	mustEmbedUnimplementedUsersProtoInterfaceServer()
}

func RegisterUsersProtoInterfaceServer(s grpc.ServiceRegistrar, srv UsersProtoInterfaceServer) {
	s.RegisterService(&UsersProtoInterface_ServiceDesc, srv)
}

func _UsersProtoInterface_GetUserByUuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uuid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersProtoInterfaceServer).GetUserByUuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flydev_chat_app_users.UsersProtoInterface/GetUserByUuid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersProtoInterfaceServer).GetUserByUuid(ctx, req.(*Uuid))
	}
	return interceptor(ctx, in, info, handler)
}

// UsersProtoInterface_ServiceDesc is the grpc.ServiceDesc for UsersProtoInterface service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsersProtoInterface_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flydev_chat_app_users.UsersProtoInterface",
	HandlerType: (*UsersProtoInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserByUuid",
			Handler:    _UsersProtoInterface_GetUserByUuid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/clients/rpc/users_client/users.proto",
}
